services:
  postgres:
    image: postgres:16-alpine
    container_name: digital_sign_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: digital_sign_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d digital_sign_db']
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - digital_sign_net

  mailpit:
    image: axllent/mailpit:v1.28
    container_name: digital_sign_mailpit
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'
    healthcheck:
      test: ['CMD', '/mailpit', 'readyz']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - digital_sign_net

  redis:
    image: redis:7-alpine
    container_name: digital_sign_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - digital_sign_net

volumes:
  postgres_data:

networks:
  digital_sign_net:
